- name: install packages
  shell:
    sudo apt install -y mariadb-server python3-pymysql

- name: Making a Configure File
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch

- name: Configure File editing
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: present
    line: "{{item}}"
  with_items:
  - [mysql]
  - bind-address = 10.0.0.11
  - |
  - default-storage-engine = innodb
  - max_connections = 4096
  - collation-server = utf8_general_ci
  - character-set-server = utf8

- name: mysql service restart
  shell:
    service mysql restart
